before:
  hooks:
  - go mod download
builds:
- id: memorybox
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    386: i386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'