name: build and test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '*'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: build and test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14.0'
    - run: go mod download
    - name: build and test
      run: |
        go build -v .
        go test -v $(go list ./... | grep -v hack) -coverprofile=profile.cov
    - name: push code coverage to coveralls.io
      if: matrix.os == 'ubuntu-latest'
      uses: shogo82148/actions-goveralls@v1.2.2
      with:
        path-to-profile: profile.cov
