name: release
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: prep-changelog
      run: git fetch --prune --unshallow
    - name: setup-go
      uses: actions/setup-go@v2-beta
      with:
        go-version: '^1.14.2'
    - name: release
      uses: goreleaser/goreleaser-action@master
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}