name: release
on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: prep-changelog
      run: git fetch --prune --unshallow
    - name: setup-go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: release
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}